/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChatMessageId = string;
export interface ChatMessageView {
  'id' : ChatMessageId,
  'content' : string,
  'recipient' : [] | [Principal],
  'sender' : Principal,
  'createdTimestamp' : Time,
}
export type CommentId = string;
export interface CommentView {
  'id' : CommentId,
  'content' : string,
  'author' : Principal,
  'createdTimestamp' : Time,
  'replies' : Array<CommentView>,
  'postId' : PostId,
}
export type ExternalBlob = Uint8Array;
export type NotificationId = string;
export type NotificationType = { 'like' : null } |
  { 'comment' : null };
export interface NotificationView {
  'id' : NotificationId,
  'notifType' : NotificationType,
  'isRead' : boolean,
  'senderPrincipal' : Principal,
  'message' : string,
  'createdTimestamp' : Time,
  'recipientPrincipal' : Principal,
  'postId' : PostId,
}
export type PostId = string;
export interface PostView {
  'id' : PostId,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'createdTimestamp' : Time,
  'comments' : Array<CommentView>,
  'imageBlobId' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'profilePhotoId' : [] | [ExternalBlob],
  'coverPhotoId' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'deleteExpiredPosts' : ActorMethod<[], undefined>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<PostView>>,
  'getGroupMessages' : ActorMethod<[bigint, bigint], Array<ChatMessageView>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationView>>,
  'getPrivateMessages' : ActorMethod<
    [Principal, bigint, bigint],
    Array<ChatMessageView>
  >,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPosts' : ActorMethod<[Principal, bigint, bigint], Array<PostView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'replyToComment' : ActorMethod<[PostId, CommentId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGroupMessage' : ActorMethod<[string], undefined>,
  'sendPrivateMessage' : ActorMethod<[Principal, string], undefined>,
  'startAutoDeleteTimer' : ActorMethod<[], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];