/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserView {
  'status' : UserStatus,
  'principal' : Principal,
  'signupDate' : Time,
  'email' : string,
  'adminRole' : UserAdminRole,
  'profile' : UserProfile,
}
export type ChatMessageId = string;
export interface ChatMessageView {
  'id' : ChatMessageId,
  'content' : string,
  'recipient' : [] | [Principal],
  'sender' : Principal,
  'createdTimestamp' : Time,
  'imageBlobId' : [] | [ExternalBlob],
}
export type CommentId = string;
export interface CommentView {
  'id' : CommentId,
  'content' : string,
  'author' : Principal,
  'createdTimestamp' : Time,
  'replies' : Array<CommentView>,
  'postId' : PostId,
}
export type ExternalBlob = Uint8Array;
export type NotificationId = string;
export type NotificationType = { 'like' : null } |
  { 'comment' : null };
export interface NotificationView {
  'id' : NotificationId,
  'notifType' : NotificationType,
  'isRead' : boolean,
  'senderPrincipal' : Principal,
  'message' : string,
  'createdTimestamp' : Time,
  'recipientPrincipal' : Principal,
  'postId' : PostId,
}
export type PostId = string;
export interface PostView {
  'id' : PostId,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'createdTimestamp' : Time,
  'comments' : Array<CommentView>,
  'imageBlobId' : [] | [ExternalBlob],
}
export type Time = bigint;
export type UserAdminRole = { 'none' : null } |
  { 'superAdmin' : null } |
  { 'helperAdmin' : null };
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'profilePhotoId' : [] | [ExternalBlob],
  'coverPhotoId' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'pending' : null } |
  { 'blocked' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[PostId, string], undefined>,
  'addReaction' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupIncompleteUsers' : ActorMethod<[], bigint>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'deleteExpiredPosts' : ActorMethod<[], undefined>,
  'deleteMessageForEveryone' : ActorMethod<[string], undefined>,
  'deleteMessageForMe' : ActorMethod<[string], undefined>,
  'emailExists' : ActorMethod<[string], boolean>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getAllUsersAdminView' : ActorMethod<[], Array<AdminUserView>>,
  'getCallerAdminRole' : ActorMethod<[], UserAdminRole>,
  'getCallerEmail' : ActorMethod<[], [] | [string]>,
  'getCallerStatus' : ActorMethod<[], UserStatus>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeletedForMe' : ActorMethod<[], Array<string>>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<PostView>>,
  'getGroupMessages' : ActorMethod<[bigint, bigint], Array<ChatMessageView>>,
  'getMessageReactions' : ActorMethod<[string], Array<[string, string]>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationView>>,
  'getPrivateMessages' : ActorMethod<
    [Principal, bigint, bigint],
    Array<ChatMessageView>
  >,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPosts' : ActorMethod<[Principal, bigint, bigint], Array<PostView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSuperAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'removeReaction' : ActorMethod<[string], undefined>,
  'replyToComment' : ActorMethod<[PostId, CommentId, string], undefined>,
  'resetPasswordForEmail' : ActorMethod<[string], undefined>,
  'saveCallerEmail' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGroupMessage' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'sendPrivateMessage' : ActorMethod<
    [Principal, string, [] | [ExternalBlob]],
    undefined
  >,
  'setHelperAdmin' : ActorMethod<[Principal, boolean], undefined>,
  'startAutoDeleteTimer' : ActorMethod<[], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'updateUserStatus' : ActorMethod<[Principal, UserStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];