/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommentView = IDL.Rec();
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserStatus = IDL.Variant({
  'pending' : IDL.Null,
  'blocked' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const UserAdminRole = IDL.Variant({
  'none' : IDL.Null,
  'superAdmin' : IDL.Null,
  'helperAdmin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'profilePhotoId' : IDL.Opt(ExternalBlob),
  'coverPhotoId' : IDL.Opt(ExternalBlob),
});
export const AdminUserView = IDL.Record({
  'status' : UserStatus,
  'principal' : IDL.Principal,
  'signupDate' : Time,
  'email' : IDL.Text,
  'adminRole' : UserAdminRole,
  'profile' : UserProfile,
});
export const CommentId = IDL.Text;
CommentView.fill(
  IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'createdTimestamp' : Time,
    'replies' : IDL.Vec(CommentView),
    'postId' : PostId,
  })
);
export const PostView = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'createdTimestamp' : Time,
  'comments' : IDL.Vec(CommentView),
  'imageBlobId' : IDL.Opt(ExternalBlob),
});
export const ChatMessageId = IDL.Text;
export const ChatMessageView = IDL.Record({
  'id' : ChatMessageId,
  'content' : IDL.Text,
  'recipient' : IDL.Opt(IDL.Principal),
  'sender' : IDL.Principal,
  'createdTimestamp' : Time,
  'imageBlobId' : IDL.Opt(ExternalBlob),
});
export const NotificationId = IDL.Text;
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : NotificationId,
  'notifType' : NotificationType,
  'isRead' : IDL.Bool,
  'senderPrincipal' : IDL.Principal,
  'message' : IDL.Text,
  'createdTimestamp' : Time,
  'recipientPrincipal' : IDL.Principal,
  'postId' : PostId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupIncompleteUsers' : IDL.Func([], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'deleteExpiredPosts' : IDL.Func([], [], []),
  'deleteMessageForEveryone' : IDL.Func([IDL.Text], [], []),
  'deleteMessageForMe' : IDL.Func([IDL.Text], [], []),
  'emailExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllUsersAdminView' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'getCallerAdminRole' : IDL.Func([], [UserAdminRole], ['query']),
  'getCallerEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerStatus' : IDL.Func([], [UserStatus], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeletedForMe' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PostView)], ['query']),
  'getGroupMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessageView)],
      ['query'],
    ),
  'getMessageReactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], ['query']),
  'getPrivateMessages' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessageView)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserPosts' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(PostView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'removeReaction' : IDL.Func([IDL.Text], [], []),
  'replyToComment' : IDL.Func([PostId, CommentId, IDL.Text], [], []),
  'resetPasswordForEmail' : IDL.Func([IDL.Text], [], []),
  'saveCallerEmail' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'sendPrivateMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'setHelperAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'startAutoDeleteTimer' : IDL.Func([], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'updateUserStatus' : IDL.Func([IDL.Principal, UserStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommentView = IDL.Rec();
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserStatus = IDL.Variant({
    'pending' : IDL.Null,
    'blocked' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserAdminRole = IDL.Variant({
    'none' : IDL.Null,
    'superAdmin' : IDL.Null,
    'helperAdmin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'profilePhotoId' : IDL.Opt(ExternalBlob),
    'coverPhotoId' : IDL.Opt(ExternalBlob),
  });
  const AdminUserView = IDL.Record({
    'status' : UserStatus,
    'principal' : IDL.Principal,
    'signupDate' : Time,
    'email' : IDL.Text,
    'adminRole' : UserAdminRole,
    'profile' : UserProfile,
  });
  const CommentId = IDL.Text;
  CommentView.fill(
    IDL.Record({
      'id' : CommentId,
      'content' : IDL.Text,
      'author' : IDL.Principal,
      'createdTimestamp' : Time,
      'replies' : IDL.Vec(CommentView),
      'postId' : PostId,
    })
  );
  const PostView = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'createdTimestamp' : Time,
    'comments' : IDL.Vec(CommentView),
    'imageBlobId' : IDL.Opt(ExternalBlob),
  });
  const ChatMessageId = IDL.Text;
  const ChatMessageView = IDL.Record({
    'id' : ChatMessageId,
    'content' : IDL.Text,
    'recipient' : IDL.Opt(IDL.Principal),
    'sender' : IDL.Principal,
    'createdTimestamp' : Time,
    'imageBlobId' : IDL.Opt(ExternalBlob),
  });
  const NotificationId = IDL.Text;
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'id' : NotificationId,
    'notifType' : NotificationType,
    'isRead' : IDL.Bool,
    'senderPrincipal' : IDL.Principal,
    'message' : IDL.Text,
    'createdTimestamp' : Time,
    'recipientPrincipal' : IDL.Principal,
    'postId' : PostId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupIncompleteUsers' : IDL.Func([], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'deleteExpiredPosts' : IDL.Func([], [], []),
    'deleteMessageForEveryone' : IDL.Func([IDL.Text], [], []),
    'deleteMessageForMe' : IDL.Func([IDL.Text], [], []),
    'emailExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllUsersAdminView' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'getCallerAdminRole' : IDL.Func([], [UserAdminRole], ['query']),
    'getCallerEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerStatus' : IDL.Func([], [UserStatus], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeletedForMe' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PostView)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessageView)],
        ['query'],
      ),
    'getMessageReactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], ['query']),
    'getPrivateMessages' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessageView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserPosts' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSuperAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'removeReaction' : IDL.Func([IDL.Text], [], []),
    'replyToComment' : IDL.Func([PostId, CommentId, IDL.Text], [], []),
    'resetPasswordForEmail' : IDL.Func([IDL.Text], [], []),
    'saveCallerEmail' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'sendPrivateMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'setHelperAdmin' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'startAutoDeleteTimer' : IDL.Func([], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'updateUserStatus' : IDL.Func([IDL.Principal, UserStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };